extends RefCounted
class_name IntroStoryData
const STORY_TEXTURES: Dictionary = {
	"res://1.Codebase/src/assets/ui/intro/intro_credits_illustration.png": preload("res://1.Codebase/src/assets/ui/intro/intro_credits_illustration.png"),
	"res://1.Codebase/src/assets/ui/intro/intro_gameplay_illustration.png": preload("res://1.Codebase/src/assets/ui/intro/intro_gameplay_illustration.png"),
	"res://1.Codebase/src/assets/ui/intro/intro_mechanics_illustration.png": preload("res://1.Codebase/src/assets/ui/intro/intro_mechanics_illustration.png"),
	"res://1.Codebase/src/assets/ui/intro/intro_stats_illustration.png": preload("res://1.Codebase/src/assets/ui/intro/intro_stats_illustration.png"),
	"res://1.Codebase/src/assets/ui/intro/intro_world_illustration.png": preload("res://1.Codebase/src/assets/ui/intro/intro_world_illustration.png"),
	"res://1.Codebase/src/assets/ui/intro/page_10_story_team.png": preload("res://1.Codebase/src/assets/ui/intro/page_10_story_team.png"),
	"res://1.Codebase/src/assets/ui/intro/page_11_story_repair.png": preload("res://1.Codebase/src/assets/ui/intro/page_11_story_repair.png"),
	"res://1.Codebase/src/assets/ui/intro/page_12_story_sit.png": preload("res://1.Codebase/src/assets/ui/intro/page_12_story_sit.png"),
	"res://1.Codebase/src/assets/ui/intro/page_13_story_disappointment.png": preload("res://1.Codebase/src/assets/ui/intro/page_13_story_disappointment.png"),
	"res://1.Codebase/src/assets/ui/intro/page_14_story_pressure.png": preload("res://1.Codebase/src/assets/ui/intro/page_14_story_pressure.png"),
	"res://1.Codebase/src/assets/ui/intro/page_15_story_submit.png": preload("res://1.Codebase/src/assets/ui/intro/page_15_story_submit.png"),
	"res://1.Codebase/src/assets/ui/intro/page_16_story_ark_notice.png": preload("res://1.Codebase/src/assets/ui/intro/page_16_story_ark_notice.png"),
	"res://1.Codebase/src/assets/ui/intro/page_17_story_saint_smile.png": preload("res://1.Codebase/src/assets/ui/intro/page_17_story_saint_smile.png"),
	"res://1.Codebase/src/assets/ui/intro/page_18_story_ark_orders.png": preload("res://1.Codebase/src/assets/ui/intro/page_18_story_ark_orders.png"),
	"res://1.Codebase/src/assets/ui/intro/page_19_story_donkey_letter.png": preload("res://1.Codebase/src/assets/ui/intro/page_19_story_donkey_letter.png"),
	"res://1.Codebase/src/assets/ui/intro/page_20_story_gda_formed.png": preload("res://1.Codebase/src/assets/ui/intro/page_20_story_gda_formed.png"),
	"res://1.Codebase/src/assets/ui/intro/page_21_story_ark_arrives.png": preload("res://1.Codebase/src/assets/ui/intro/page_21_story_ark_arrives.png"),
	"res://1.Codebase/src/assets/ui/intro/page_22_story_donkey_entrance.png": preload("res://1.Codebase/src/assets/ui/intro/page_22_story_donkey_entrance.png"),
	"res://1.Codebase/src/assets/ui/intro/page_23_story_fake_detector.png": preload("res://1.Codebase/src/assets/ui/intro/page_23_story_fake_detector.png"),
	"res://1.Codebase/src/assets/ui/intro/page_24_story_safety_map.png": preload("res://1.Codebase/src/assets/ui/intro/page_24_story_safety_map.png"),
	"res://1.Codebase/src/assets/ui/intro/page_25_story_map_ignored.png": preload("res://1.Codebase/src/assets/ui/intro/page_25_story_map_ignored.png"),
	"res://1.Codebase/src/assets/ui/intro/page_26_story_radio_exclusion.png": preload("res://1.Codebase/src/assets/ui/intro/page_26_story_radio_exclusion.png"),
	"res://1.Codebase/src/assets/ui/intro/page_27_story_german_commands.png": preload("res://1.Codebase/src/assets/ui/intro/page_27_story_german_commands.png"),
	"res://1.Codebase/src/assets/ui/intro/page_28_story_blocking_one.png": preload("res://1.Codebase/src/assets/ui/intro/page_28_story_blocking_one.png"),
	"res://1.Codebase/src/assets/ui/intro/page_29_story_gloria_pua.png": preload("res://1.Codebase/src/assets/ui/intro/page_29_story_gloria_pua.png"),
	"res://1.Codebase/src/assets/ui/intro/page_30_story_blast_door.png": preload("res://1.Codebase/src/assets/ui/intro/page_30_story_blast_door.png"),
	"res://1.Codebase/src/assets/ui/intro/page_31_story_donkey_runs.png": preload("res://1.Codebase/src/assets/ui/intro/page_31_story_donkey_runs.png"),
	"res://1.Codebase/src/assets/ui/intro/page_32_story_one_lifting_door.png": preload("res://1.Codebase/src/assets/ui/intro/page_32_story_one_lifting_door.png"),
	"res://1.Codebase/src/assets/ui/intro/page_33_story_protagonist_rage.png": preload("res://1.Codebase/src/assets/ui/intro/page_33_story_protagonist_rage.png"),
	"res://1.Codebase/src/assets/ui/intro/page_34_story_gloria_disappointing_gaze.png": preload("res://1.Codebase/src/assets/ui/intro/page_34_story_gloria_disappointing_gaze.png"),
	"res://1.Codebase/src/assets/ui/intro/page_35_story_protagonist_breakdown.png": preload("res://1.Codebase/src/assets/ui/intro/page_35_story_protagonist_breakdown.png"),
	"res://1.Codebase/src/assets/ui/intro/page_36_story_submission_apology.png": preload("res://1.Codebase/src/assets/ui/intro/page_36_story_submission_apology.png"),
	"res://1.Codebase/src/assets/ui/intro/page_37_story_greenhouse_return_ceremony_setup.png": preload("res://1.Codebase/src/assets/ui/intro/page_37_story_greenhouse_return_ceremony_setup.png"),
	"res://1.Codebase/src/assets/ui/intro/page_39_story_protagonist_pov_brainwashed.png": preload("res://1.Codebase/src/assets/ui/intro/page_39_story_protagonist_pov_brainwashed.png"),
	"res://1.Codebase/src/assets/ui/intro/page_40_story_departure_one_luggage.png": preload("res://1.Codebase/src/assets/ui/intro/page_40_story_departure_one_luggage.png"),
	"res://1.Codebase/src/assets/ui/intro/page_1_story_intro.png": preload("res://1.Codebase/src/assets/ui/intro/page_1_story_intro.png"),
	"res://1.Codebase/src/assets/ui/intro/page_2_story_doubt.png": preload("res://1.Codebase/src/assets/ui/intro/page_2_story_doubt.png"),
	"res://1.Codebase/src/assets/ui/intro/page_3_story_camp.png": preload("res://1.Codebase/src/assets/ui/intro/page_3_story_camp.png"),
	"res://1.Codebase/src/assets/ui/intro/page_4_story_gloria.png": preload("res://1.Codebase/src/assets/ui/intro/page_4_story_gloria.png"),
	"res://1.Codebase/src/assets/ui/intro/page_5_story_walk.png": preload("res://1.Codebase/src/assets/ui/intro/page_5_story_walk.png"),
	"res://1.Codebase/src/assets/ui/intro/page_6_story_soften.png": preload("res://1.Codebase/src/assets/ui/intro/page_6_story_soften.png"),
	"res://1.Codebase/src/assets/ui/intro/page_7_story_deeptalk.png": preload("res://1.Codebase/src/assets/ui/intro/page_7_story_deeptalk.png"),
	"res://1.Codebase/src/assets/ui/intro/page_8_story_superior.png": preload("res://1.Codebase/src/assets/ui/intro/page_8_story_superior.png"),
	"res://1.Codebase/src/assets/ui/intro/page_9_story_greenhouse.png": preload("res://1.Codebase/src/assets/ui/intro/page_9_story_greenhouse.png"),
	"res://1.Codebase/src/assets/ui/intro/page_41_story_final_logo.png": preload("res://1.Codebase/src/assets/ui/intro/page_41_story_final_logo.png"),
}
const STORY_PAGES: Array[Dictionary] = [
	{
		"title_zh": "INTRO_DATA_PAGE_1_TITLE",
		"title_en": "Page 1",
		"text_zh": "INTRO_DATA_PAGE_1_TEXT",
		"text_en": "Scene: Boundary Ruins No. 1. The sky is perpetually shrouded in thick acidic smog, surrounded by rusted steel wreckage.\nVisual: The protagonist and their old friend One sit under a shelter pieced together from scrap metal. One is the only comrade the protagonist trusts in this wasteland; always quiet, currently bent over, silently repairing a protective suit.\nSuddenly, a scratched public holographic radio outside the shelter emits a harsh electrical noise. Then, an extremely gentle, sweet pop melody, completely out of place among the ruins, begins to play.\nHolographic Radio (Teacher Chan's voice singing):\n\"No matter what you do, no one believes in you...\"\n\"Everyone can shine, as long as you find the right place...\"\n\"Let me be my own protagonist...\"\n\"Success or failure depends on how I see it...\"\nVisual: The protagonist frowns, watching the holographic image of Teacher Chan projected by the radio. She wears a pure white dress, appearing impossibly sacred amid the radiation-filled projection.",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_1_story_intro.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_2_TITLE",
		"title_en": "Page 2",
		"text_zh": "INTRO_DATA_PAGE_2_TEXT",
		"text_en": "Holographic Radio (Teacher Chan's broadcast monologue):\n\"Dear lost souls wandering in the ruins, hello. Perhaps you've already noticed that the resources of this world are depleting, and the end of 'entropy towards nothingness' is approaching. Yes, the old world is collapsing... but do not fear!\"\nHolographic Radio (Teacher Chan clasps her hands together, smiling warmly):\n\"As long as we entrust everything to the 'Flying Spaghetti Monster (FSM)', miracles will come. Remember, the law of the universe is the 'Law of Attraction'! As long as you maintain absolute positive energy and reject all negative emotions, beautiful things will be drawn to you. Don't let yourself be buried by worldly judgments, if you believe, charge forward fearlessly!\"\nProtagonist (muttering sarcastically): \"'Success or failure depends on how I see it'? If I don't admit I'm hungry, will my stomach stop hurting? What nonsense. I don't believe it at all, and who knows if the world is really ending, maybe it'll be another thousand or ten thousand years.\"\nVisual: Despite the words, months of survival pressure and helplessness have left a trace of faint exhaustion in the protagonist's eyes. They turn to look at One, who simply stops working and forces a gentle, noncommittal smile.",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_2_story_doubt.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_3_TITLE",
		"title_en": "Page 3",
		"text_zh": "INTRO_DATA_PAGE_3_TEXT",
		"text_en": "Scene: Ruins Market, Scavenger Camp.\nVisual: After the broadcast ends, One stands up and gently pats the protagonist's shoulder. He gestures, pointing toward a solitary figure at the edge of the camp.\nProtagonist (understanding One's gesture, frowning): \"You want to help her? One, you're always so kind. But we're barely surviving ourselves. Over the past few years, I've been betrayed too many times by selfish outsiders. Only you I trust, I can't trust anyone else here.\"\nVisual: One doesn't speak, just looks at the protagonist with pleading, sincere eyes. One knows the girl has just drifted into this wasteland, unfamiliar with everything, without someone to guide her, she won't survive. One expresses his wish to travel with her and hopes the protagonist will join them, watching out for each other.\nProtagonist (sighing, tone softening): \"Since it's you asking... fine. In this godforsaken place, I only trust you. If you think she's okay, then let's go together.\"",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_3_story_camp.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_4_TITLE",
		"title_en": "Page 4",
		"text_zh": "INTRO_DATA_PAGE_4_TEXT",
		"text_en": "Visual: One smiles with relief and walks toward the corner of the camp. Soon, he returns with a girl wearing a clean white cloak. In this filthy wasteland, her cleanliness seems almost unreal. This is Gloria.\nGloria (approaching them, not showing the usual scavenger wariness but wearing a gentle smile): \"Hello, thank you for being willing to take me along. I just arrived here and don't understand much yet.\"\nVisual: The protagonist turns away to organize equipment parts on the ground, deliberately avoiding her gaze, appearing extremely cold and passive.\nProtagonist (not looking up, tone curt): \"Thank him (pointing to One), not me. He's the one helping you. Stay close when we're on the road and don't cause trouble.\"\nGloria (smile unchanged, nodding gently): \"Okay, I hope we can work well together.\"\nVisual: The protagonist doesn't initiate further conversation with her, doesn't even look at her properly. The protagonist's inner monologue emerges: [I'm only agreeing because of One. I absolutely won't let my guard down with strangers easily.]",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_4_story_gloria.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_5_TITLE",
		"title_en": "Page 5",
		"text_zh": "INTRO_DATA_PAGE_5_TEXT",
		"text_en": "Scene: On the desolate road toward \"Stanfield National Park.\"\nVisual: This isn't a mission, just an escape from the oppressive camp. The three wander aimlessly toward an abandoned park where mutated cattle and sheep were reportedly seen, killing time. One silently walks ahead scouting, while the protagonist deliberately lags behind, maintaining a safe distance from the girl in the white cloak.\nSuddenly, Gloria slows down and falls back beside the protagonist. She turns her head and, without warning, looks directly into the protagonist's eyes, breaking into a brilliant smile.\nGloria (speaking softly, with a hint of playfulness):\n\"Btw, we haven't actually introduced ourselves properly these past few days [laugh]. I just noticed the old district badge on your jacket... what a coincidence, I found out we're both from the 'Financial Center Ruins.' And also, I see you're always quietly observing your surroundings... I'm also a 6767 personality type.\"\nVisual: The protagonist abruptly stops, pupils contracting slightly, as if struck by lightning.\nProtagonist (inner turmoil): [6767? The rarest soul frequency in this wasteland, prone to internal conflict and desperately craving understanding? I once wished in this barren place to meet someone who understood me... could she really be like me?]",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_5_story_walk.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_6_TITLE",
		"title_en": "Page 6",
		"text_zh": "INTRO_DATA_PAGE_6_TEXT",
		"text_en": "Visual: The protagonist looks up at this girl with a pure smile. Their previously cold, defensive gaze instantly softens, unconsciously applying a benevolent filter labeled \"kindred spirit.\"\nProtagonist (tone becoming somewhat awkward, unable to hide surprise): \"Actually... were you walking behind me the whole time? Sorry I was so cold to you before. I just... don't have much confidence in people here.\"\nGloria (shaking her head gently, eyes clear and full of understanding): \"It's okay. I know you're just protecting yourself. We 6767 types can always immediately sense the malice around us, so we build walls, right?\"\nVisual: This sentence precisely strikes the softest place in the protagonist's heart. The long-standing loneliness seems to have found an outlet.\nOne, walking ahead, hears the conversation and slows down, turning back to give the protagonist an encouraging smile. The three come to a dead tree and sit down on the ground.",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_6_story_soften.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_7_TITLE",
		"title_en": "Page 7",
		"text_zh": "INTRO_DATA_PAGE_7_TEXT",
		"text_en": "Scene: Under a dead tree at Stanfield National Park.\nVisual: No cattle or sheep, just desolation everywhere. But the protagonist doesn't care, they begin what they consider a \"soul resonance\" deep talk.\nProtagonist (dropping all defenses, tone low): \"You don't know what I've been through. At my previous camp, I was isolated and betrayed by the comrades I trusted most. There are no absolutely good people in this world. I can only rely on cold logic to guard against everyone, or I'll die miserably.\"\nGloria (listening quietly, eyes full of compassion. She reaches out and gently pats the protagonist's hand):\n\"You've been through so much. I'll listen to however much you want to say. But you know what? The reason you're in such pain is because you haven't yet understood the truth in Teacher Chan's broadcast.\"\nProtagonist (frowning slightly, rationality partially returning): \"Teacher Chan? That cult broadcast telling everyone to abandon thinking and believe in some Flying Spaghetti Monster (FSM)? That's all deceptive nonsense. I don't believe in that.\"",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_7_story_deeptalk.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_8_TITLE",
		"title_en": "Page 8",
		"text_zh": "INTRO_DATA_PAGE_8_TEXT",
		"text_en": "Visual: Gloria doesn't get angry. Instead, she looks at the protagonist and One with a superior gaze, as if viewing lost lambs.\nGloria (tone becoming sacred and oppressive):\n\"That's not a cult, that's the frequency of the universe. You two are both exhausted because you always think the world is full of malice. Actually, everything that happens in life, every person you meet, has its purpose. Those betrayals you experienced were just tests given to you by the Flying Spaghetti Monster and FSM.\"\nGloria (staring at the protagonist, delivering a statement heavily laden with manipulation):\n\"Actually, most of the time, if you just treat others with kindness, don't stab people in the back, and don't have such a heavy heart of hatred, people won't dislike you. The reason you were excluded is because your negative energy is too strong. Don't overthink things and stress yourself out to death.\"\nVisual: The protagonist is slightly stunned. This statement is logically \"victim-blaming\" (you were excluded because you weren't kind enough). But in that moment of desperately wanting to be accepted by this \"kindred spirit,\" the protagonist's brain starts to malfunction.",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_8_story_superior.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_9_TITLE",
		"title_en": "Page 9",
		"text_zh": "INTRO_DATA_PAGE_9_TEXT",
		"text_en": "Scene: Gloria's makeshift shelter, \"The Beautiful Greenhouse.\"\nVisual: After the walk, Gloria brings them to her personal shelter pieced together from garbage. A tattered piece of cardboard hangs here, and though there's no wi-fi, there's a logo that looks like a wi-fi symbol reading: \"CONNECT TO FSM, Password: PRAYER.\"\nInside the greenhouse, a dim lamp is lit, its shade crudely made by wrapping waste \"Life Bread\" packaging paper around a heating bulb; nearby is a mold-covered old pair of pants stuffed with cotton to serve as a pillow.\nProtagonist (looking at the bread-wrapper lampshade that could catch fire any moment, rational instinct struggling again): \"Wait... this lampshade is a fire hazard! And those moldy pants, this completely violates hygiene and safety logic!\"\nGloria (hands clasped at her chest, looking at the protagonist like a saint, tone incredibly gentle yet filled with unquestionable pressure):\n\"See, your negative energy is showing again. These are clearly good things, you should be grateful. I've transformed this abandoned garbage into art filled with warmth. This is the magic of rebirth. I'm practically a wizard.\"\nGloria (suddenly approaching the protagonist, eyes gleaming with fervent light):\n\"You don't believe Teacher Chan's words, don't believe in the Flying Spaghetti Monster (FSM)... but think about it, why, on this vast wasteland, did the three of us specifically meet? Why would you, someone so guarded who no longer trusts anyone, happen to encounter me, a 6767 kindred spirit who can completely understand you?\"",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_9_story_greenhouse.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_10_TITLE",
		"title_en": "Page 10",
		"text_zh": "INTRO_DATA_PAGE_10_TEXT",
		"text_en": "Visual: The protagonist freezes, recalling today's miracle-like encounter, a crack appearing in their rational defenses.\nGloria (spreading her arms, declaring passionately):\n\"This is absolutely not a coincidence! This is iron-clad proof that the 'Law of Attraction' is working! Because I pray every day, every day I emit the purest positive energy to the universe, so FSM heard my voice and precisely attracted you to my side!\"\nGloria (extending her hand, gesturing for the protagonist and One to join hands):\n\"The facts are right before your eyes, the laws of the universe are real! Let go of those cold, useless aggressive thoughts. Since FSM brought us together, as long as we entrust what we can't handle to Him and continue maintaining absolute positive energy, we can rebuild this broken world. The three of us, forming the 'Glorious Deliverance Agency (GDA)', okay?\"\nVisual: Gloria turns her head, her gaze sweeping over One.\nOne (afraid of disrupting this 'sacred' atmosphere, bowing his head, compliantly saying softly): \"...Mm, it's warm, I'm fine, I think this arrangement is good.\"\nVisual: The protagonist looks at Gloria's incredibly sincere eyes, then turns to look at One who has already chosen to compromise.\nThe protagonist's inner turmoil: On one side, common sense and logic are screaming warnings; on the other, the so-called \"destined Law of Attraction\" and the hard-found INFJ soulmate.\nProtagonist (inner monologue): [Even such an incredible meeting has happened... maybe she's right, maybe it really is because I'm too negative that I've been living in hell. If this is the price of being accepted by a kindred spirit... then I'd rather abandon thinking.]\nProtagonist (taking a deep breath, actively cutting off rational alarms, placing their hand forward, forcing a smile): \"Okay, I believe you... I believe this is our fate. Let's form a team.\"\nVisual: The three form a circle under the Life Bread lamp light that could catch fire any moment, Gloria revealing a victorious, loving smile.\nThe \"Glorious Deliverance Agency (GDA1)\" is thus established. For that illusory resonance packaged as a \"cosmic miracle\" through manipulation, the protagonist has personally pushed themselves into a bottomless abyss called \"toxic positivity.\"\n[Pages 1-10 Complete, Act I: The Fatal Honeymoon Ends]",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_10_story_team.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_11_TITLE",
		"title_en": "Page 11",
		"text_zh": "INTRO_DATA_PAGE_11_TEXT",
		"text_en": "Scene: Late night at the 'Greenhouse' shelter.\nVisual: Outside, a corrosive wasteland sandstorm rages. The protagonist works anxiously to repair a broken water purifier, without it, they'll face organ failure from contaminated water.\nProtagonist: 'The filter is completely broken. If we don't go to the West District Scrapyard tomorrow to find replacement parts, we'll die of heavy metal poisoning the day after.'\nGloria suddenly places her hand on the protagonist's, taking away the tools with a saintly expression.",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_11_story_repair.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_12_TITLE",
		"title_en": "Page 12",
		"text_zh": "INTRO_DATA_PAGE_12_TEXT",
		"text_en": "Gloria: 'Stop. Listen to the wind, it's so violent because your anxiety is disturbing our greenhouse's magnetic field.'\nProtagonist (stunned): 'But... this isn't anxiety, this is objective survival data. The purifier is broken, this is a physical problem that must be solved!'\nGloria: 'You're trapped in that cold, pessimistic thinking again. This is why you suffered so much before. Come, sit beside me. It's time for our 'Gratitude and Entrustment' session.'\nGloria pats the ground, gesturing for the protagonist and One to sit. One obediently puts down his knife and sits. The protagonist, suppressing anxiety for the sake of this newfound 'kindred spirit' friendship, reluctantly sits down.",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_12_story_sit.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_13_TITLE",
		"title_en": "Page 13",
		"text_zh": "INTRO_DATA_PAGE_13_TEXT",
		"text_en": "Gloria (hands clasped, eyes closed, voice hypnotic): 'In this hellish place, we encounter many seemingly terrible things every day. But actually, these are all lessons from the universe. So every night I give thanks and entrust what I cannot handle to the Flying Spaghetti Monster (FSM).'\nGloria (opening eyes, staring directly at protagonist): 'Tell me, what is the problem you 'cannot handle'? Say it out loud, then give it to FSM.'\nProtagonist (taking a deep breath, trying to reason): 'What I can't handle is this water purifier. Without a filter, it can't purify radioactive water. FSM is a spiritual belief, He can't conjure a physical filter out of thin air. What we need is tomorrow's action plan, not sitting here praying.'\nVisual: The air suddenly goes quiet. Gloria's smile slowly disappears, a flash of hurt and profound disappointment crossing her eyes.",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_13_story_disappointment.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_14_TITLE",
		"title_en": "Page 14",
		"text_zh": "INTRO_DATA_PAGE_14_TEXT",
		"text_en": "Gloria (lowering her head slightly, voice becoming aggrieved, deploying moral blackmail): 'You think this is just about a filter? No... your powerful negative energy is destroying this hard-won home. You're always complaining about 'can't do it' and 'it's dangerous', you're questioning the universe's arrangements and questioning my purpose in building this team.'\nProtagonist (feeling absurd): 'I'm not questioning you! I'm just stating an objective fact of life and death! Is pointing out problems also negative energy?'\nGloria (looking up sharply, tone severe and heavily manipulative): 'Facts? What are facts? Is your fear the fact? Do you know that your mentality of always focusing on the 'bad side' is slowly dragging me into an emotional low point? I worked so hard to build this greenhouse with love and tolerance, and you insist on tearing it apart with harmful thoughts!'\nGloria turns to One: 'One, do you also think we'll die without a filter? Do you also think the universe will abandon us?'\nOne (body trembling, looking between the aggrieved Gloria and anxious protagonist, choosing peace, silently lowers his head): '...'",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_14_story_pressure.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_15_TITLE",
		"title_en": "Page 15",
		"text_zh": "INTRO_DATA_PAGE_15_TEXT",
		"text_en": "Visual: The protagonist looks at One in disbelief. One's compromise instantly drains the last bit of courage to stick to logic. In Gloria's narrative, the protagonist has become the 'perpetrator' who destroys team harmony and hurts teammates' feelings.\nGloria (resuming her loving expression, gently grasping the protagonist's stiff hand): 'See, as long as we have the will to sacrifice and tolerate, the problem doesn't exist. Don't let your hatred and fear be so great. Try to forget the logic behind and work on the faith ahead. As long as you're a good person and believe in FSM, miracles will happen tomorrow.'\nGloria (with an almost commanding gentle tone): 'Now, say with me: Thank you FSM for the test, I am willing to let go of all anxiety.'\nVisual: The storm still rages outside, the purifier's red light still silently flashing. The protagonist looks at Gloria's expectant eyes, then at One who's willingly not fighting for anything.\nA deep sense of suffocation wells up. The protagonist realizes there might be a need to try.\nProtagonist (voice hoarse, submitting to this mental control, mechanically repeating): '...Thank you FSM for the test, I am willing to... let go of all anxiety.'\nVisual: Gloria smiles with satisfaction, the greenhouse once again filled with the false peace of 'toxic positivity.' But in the protagonist's heart, there's still a confused feeling.\nScreen slowly darkens, subtitles emerge: [The Next Day: The Miracle Didn't Come, But 'Heroes' Did.]\n[Pages 11-15 Complete, Fatal PUA Night Ends]",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_15_story_submit.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_16_TITLE",
		"title_en": "Page 16",
		"text_zh": "INTRO_DATA_PAGE_16_TEXT",
		"text_en": "Scene: Next morning at the 'Greenhouse.'\nVisual: The water purifier has completely stopped working, emitting a burnt smell. The protagonist, lips cracked from dehydration, prepares to check the rusty 'Agency Dispatch Printer' (GDA's device for issuing scavenging permits) for water source commissions.\nSuddenly, the printer emits harsh gear-grinding sounds and spits out a red-stamped cowhide paper.\nThe protagonist tears off the paper, which reads: [Personnel Change Notice: Scavenger codenamed 'ARK' has been forcibly filled into your squad's vacancy through FSM's special approval loophole.]\nProtagonist (jumping up, gripping the paper tightly): 'Who the hell is this?! One, did you submit a recruitment application to the agency? Do you know him?'\nOne (looking bewildered, shaking his head, signing): '(No, I've never even heard this name.)'\nProtagonist (grinding teeth, slapping the paper on the table): 'A complete stranger, no greeting, just barging through backdoor channels into our team? Look at this attached personnel file, completely blank resume, not even a headshot, the only stamp date is this morning! This is definitely trouble!'",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_16_story_ark_notice.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_17_TITLE",
		"title_en": "Page 17",
		"text_zh": "INTRO_DATA_PAGE_17_TEXT",
		"text_en": "Visual: Gloria, having just finished her morning prayer in the corner, walks over with a saintly smile, gently picking up the cowhide paper.\nGloria (looking at the name, hands clasped at chest, eyes shining): 'Ark (Noah's Ark)... such a sacred name. You see, this is the 'Law of Attraction' at work! Just last night we entrusted our worries to FSM, and today He personally performs a miracle, arranging a new family member for us. This is the grace of the Flying Spaghetti Monster!'\nProtagonist (suppressing fury, trying to reason): 'Gloria, this isn't a miracle! We don't know him at all, don't know his background. In the wasteland, exposing your back to a stranger with no manners and unknown background equals suicide!'\nGloria (frowning slightly, tone carrying a hint of reproach): 'Why do you always think the worst of people? Maybe he's just a lonely soul looking for shelter. We should embrace him, give him love.'",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_17_story_saint_smile.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_18_TITLE",
		"title_en": "Page 18",
		"text_zh": "INTRO_DATA_PAGE_18_TEXT",
		"text_en": "Visual: Just then, the dispatch printer 'ka-chak ka-chak' sounds again. A remote telegraph from new member 'ARK' arrives.\nNo 'hello,' no 'please take care of me', the paper tape only prints a few cold commands.\nThe printer spits out: 'Team confirmed. Today's mission: Head to West District Scrapyard. I've already formulated a complete strategic schedule. Meet at scrapyard entrance at 12:00.'\n(Pause two seconds, machine spits another segment)\n'Wait, 12:00 might need to eat, change to 12:30.'\n(Pause three more seconds)\n'No, I still need to repair equipment. 13:00 meeting. Report immediately after reading.'\nProtagonist (laughing bitterly with anger, pointing at the pile of paper scraps): 'Is this guy sick?! He just joined, not even introducing himself, directly seizing the leader position and giving orders? And changed the meeting time three times, we haven't said a single word, and he's already made all the arrangements in a black box?!'\nGloria (gently patting the protagonist's arm, softly soothing): 'Relax. He's willing to proactively arrange the schedule, proving he's very responsible! We just need to obediently follow, wouldn't that be easier? Don't always feel others are targeting you, he just has more leadership talent.'",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_18_story_ark_orders.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_19_TITLE",
		"title_en": "Page 19",
		"text_zh": "INTRO_DATA_PAGE_19_TEXT",
		"text_en": "Visual: The protagonist is rendered speechless by Gloria's 'turning disasters into blessings' logic. One silently picks up a pen and signs the consent form, once again choosing compromise.\nThe protagonist is about to explode when suddenly a mechanical messenger pigeon, quite possibly guided by the non-existent Flying Spaghetti Monster, flies in from outside the door, heavily slamming a parchment letter onto the table.\nThe envelope reads: [Application to Join from 'Glory Knight Donkey']\nVisual: The protagonist tears open the letter and reads aloud:\n'To the members of GDA1: I am a hero cursed by fate. My previous teammates were all a bunch of selfish, incompetent wastes! I bore all the hard work, but they dragged down my great plan to save the princess with their stupidity! I'm fed up with those burdens. I saw your team has a vacancy, so I've decided to grant you the honor of fighting alongside me. Immediately approve my joining.'\nProtagonist (dumbfounded, throwing the letter on the table): 'What kind of weirdo is this?! The entire letter is trampling on former teammates, pushing off all responsibility! This kind of person who only shifts blame, with a head full of feudal fairy tales and delusions of grandeur, absolutely cannot let him in!'",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_19_story_donkey_letter.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_20_TITLE",
		"title_en": "Page 20",
		"text_zh": "INTRO_DATA_PAGE_20_TEXT",
		"text_en": "Gloria (holding the letter, eyes welling with sympathetic tears): 'Oh my, he's so pitiful. He must have suffered great grievances in his previous team to write such a defensive letter. He's just a wounded hero longing to be accepted. This is also FSM's test for us, we must heal him with love.'\nProtagonist (losing it, snatching back the application): 'Gloria! Wake up! Every line of this is shirking responsibility. This kind of person will sell us out first when something goes wrong! I'm going to tear up this application right now!'\nVisual: As the protagonist prepares to destroy the letter, the dispatch printer suddenly emits an extremely harsh long beep, spitting out one last paper with an official steel seal.\nThe paper reads: [GDA1 File Update: New member 'Donkey' has successfully joined the team. Approver: Squad Strategist ARK. Team assembly complete.]\nProtagonist (eyes wide with shock): 'Ark?! How dare he bypass us and directly submit approval to FSM?!'\nGloria (happily clapping hands, smile dazzlingly suffocating): 'Wonderful! Ark is so decisive. Now we have a responsible strategist and a wounded hero. See, as long as we have love in our hearts without prejudice, the universe will send us the best team! GDA1, officially setting out today!'\nVisual: The protagonist stands in place, looking at Ark's cold command notes, at Donkey's absurd responsibility-shifting letter, then at Gloria's face full of 'love and tolerance' and silently bowing One.\nThe protagonist knows this isn't some cosmic blessing. This is a ghost ship hijacked by so-called 'miracles' and 'positive energy,' sailing toward destruction.\n[Pages 16-20 Complete, Act II: Toxic Teammates Assemble Ends]",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_20_story_gda_formed.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_21_TITLE",
		"title_en": "Page 21",
		"text_zh": "INTRO_DATA_PAGE_21_TEXT",
		"text_en": "Scene: West District Scrapyard entrance. Acid rain just stopped, ground full of mud. 13:00.\nVisual: Protagonist and One arrive on time. Not far away stands a man wrapped like an iron barrel with a thick square gas mask, this is ARK. He holds a stack of densely gridded paper schedules.\nARK (voice muffled through mask, stiff and monotone): 'GDA1 squad. I am the strategic officer Ark for this operation. This is my 'Absolute Order Route Map' planned for the scrapyard. Do you have any opinions? We are a democratic team, welcome to propose.'\nProtagonist (taking the schedule, frowning): 'This route has problems. You're directing us toward the 'High Radiation Swamp Zone.' I checked the scrapyard terrain last night, taking the abandoned elevated bridge on the east is safe. This route is suicide.'\nARK (pushing his gas mask, checking a box on the schedule): 'Mm, I heard your opinion. However, I already submitted this route map as the final resolution to the agency system and locked it ten minutes ago. So we'll still follow my route. Let's go.'\nProtagonist (stunned): 'Then why the hell did you just ask for my opinion?! You call this democracy? This is a complete black box operation!'",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_21_story_ark_arrives.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_22_TITLE",
		"title_en": "Page 22",
		"text_zh": "INTRO_DATA_PAGE_22_TEXT",
		"text_en": "Visual: As the protagonist prepares to blow up, a man wearing flashy, shiny armor (actually made from hammered waste aluminum cans) with a tattered red cloth swaggers over. This is 'Glory Knight Donkey.'\nDonkey (striking an exaggerated heroic sword-drawing pose, loudly proclaiming): 'The gears of fate begin to turn! The dragon's roar echoes in the abyss! Everyone, Glory Knight Donkey makes his dazzling entrance! In this scrapyard, there must be a pure princess imprisoned waiting for me to rescue!'\nProtagonist (painfully clutching forehead): 'This is a scrapyard! Only rusty metal sheets and mutated rats! Where are these princesses and dragons you're talking about? Is there something wrong with your brain?'\nGloria (walking up with a bright smile, hands clasped looking at Donkey): 'Oh my, Donkey, your energy frequency is so high! Look at the light shining in his eyes, this is the heroic spirit our team needs. We can't use worldly perspectives to limit his imagination.'",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_22_story_donkey_entrance.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_23_TITLE",
		"title_en": "Page 23",
		"text_zh": "INTRO_DATA_PAGE_23_TEXT",
		"text_en": "Visual: The protagonist takes a deep breath, deciding to give up arguing common sense with them, turning instead to handle the immediate survival problem.\nProtagonist (calming down): 'Whatever. But entering the radiation zone requires a 'detector.' Our team's quota is long used up. Without a detector, going in is suicide.'\nGloria (suddenly pulling out a rusty tin can from her white cloak, smiling sweetly): 'Don't worry, leave it to me! Yesterday I met a wandering merchant and traded half our team's rations for this 'Soul Detector'!'\nVisual: The protagonist takes the tin can. It's not a detector at all, just a broken can with a crooked sunflower painted in cheap watercolor, and English chicken soup written on the bottom: 'Be your own sunshine.'\nProtagonist (hands trembling with anger): 'Gloria! You've been scammed! This is just broken garbage! The pointer inside is painted on! You traded half our survival rations for trash?!'",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_23_story_fake_detector.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_24_TITLE",
		"title_en": "Page 24",
		"text_zh": "INTRO_DATA_PAGE_24_TEXT",
		"text_en": "Gloria (smile not diminishing, looking at protagonist with compassionate eyes): 'Scammed? Why use such a negative word? Though it doesn't have what the worldly define as 'function,' it's an environmentally-friendly art piece full of stories! When you feel fear in the scrapyard, looking at this sunflower, you can find inner light.'\nGloria (approaching protagonist, tone gentle yet carrying strong manipulation): 'You're too obsessed with 'useful' and 'useless.' Your anger is actually a projection of your inner lack of security. As long as we have light in our hearts and don't admit this is a scam, it's a gift from FSM. You must learn gratitude.'\nVisual: The protagonist is shocked speechless by this 'forcibly turning bad into good' logic. Knowing reasoning with these people is useless, they can only rely on themselves.\nProtagonist (grinding teeth, pulling from backpack a hand-drawn detailed map and safety guidelines worked on all last night): 'Enough. I don't want to hear your spiritual chicken soup. I stayed up all night comparing three years of scavenging data and drew this 'Safety Avoidance Map,' marking all hidden toxic pits. Each of you take one, follow the markers and we can survive.'",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_24_story_safety_map.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_25_TITLE",
		"title_en": "Page 25",
		"text_zh": "INTRO_DATA_PAGE_25_TEXT",
		"text_en": "Visual: The protagonist hands over the life-saving map condensing so much effort to teammates. This is the greatest effort made for team survival.\nDonkey (casually taking the map, not even looking, directly folding it into a paper airplane and forcefully throwing it into the air): 'I don't see any map. Are there even maps? Seems like no one has gone in before, so there aren't any. Why don't we just go in directly!'\nARK (not even extending a hand, coldly saying through the mask): 'I also don't see any map. You didn't see it either, right? There probably was never anyone who went in before, so there isn't one.'\nGloria (not seeing the map): 'Never mind, then let's just go in directly ourselves. As long as we set out with love and tolerance, we have nothing to fear. Let's go!'\nVisual: The protagonist freezes in place. The life-saving map worked on all night is trampled in the mud, no one looks at it, no one even knows, no one cares. One hasn't had time to respond before being pulled away by Gloria with a smile.\nThe protagonist watches these teammates cheerfully walking toward the death swamp. Deep inside, a chill called 'exhaustion and despair' completely consumes them.\n[Pages 21-25 Complete, Act III: Casting Pearls Before Swine Ends]",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_25_story_map_ignored.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_26_TITLE",
		"title_en": "Page 26",
		"text_zh": "INTRO_DATA_PAGE_26_TEXT",
		"text_en": "Scene: Inside West District Scrapyard, Contamination Sorting Area.\nVisual: Surroundings piled with faintly glowing radioactive waste. The squad faces their first cooperation task: clearing a safe passage to the core area.\nThe protagonist prepares to spread out the hand-drawn map to assign positions, but ARK suddenly pulls out three sets of old tactical radio microphones just found from his backpack. Without hesitation, he hands two sets to Gloria and Donkey, putting on the last set himself. The three immediately form a tight small circle, backs turned to the protagonist and One.\nProtagonist: 'Ark, what are you doing? We have five people here. You only take three microphones for connection, why separate us?'\nARK (turning head, tone full of blind confidence and dismissiveness): 'No worries. Equipment is limited. I already have the perfect plan in mind, leave it to me. You don't need to worry about details.'",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_26_story_radio_exclusion.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_27_TITLE",
		"title_en": "Page 27",
		"text_zh": "INTRO_DATA_PAGE_27_TEXT",
		"text_en": "Visual: Something even more absurd happens. To prevent One without a microphone from understanding their 'perfect plan,' ARK actually starts loudly issuing commands in broken German.\nARK (shouting into microphone, deliberately showing off): 'Das war ein Befehl! Ich habe das 2024 gemacht! (This is an order! I did it this way in 2024!)'\nThough the protagonist can understand German from studying abroad, One cannot. Outside their three-person circle, One, without a radio and unable to understand this conversation, stands awkwardly in the muddy water like a transparent person, at a loss.",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_27_story_german_commands.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_28_TITLE",
		"title_en": "Page 28",
		"text_zh": "INTRO_DATA_PAGE_28_TEXT",
		"text_en": "Visual: One tries to step closer to hear what they're planning, but ARK deliberately turns around, using his wide back to block him. One's eyes dim, silently retreating to his original position.\nProtagonist (pulling ARK aside, roaring): 'What the hell are you doing?! We're a team! One can't understand your damn language, you won't even share microphones with us! You won't even disclose the plan, are you deliberately excluding him?!'\nARK (spreading hands, expression of 'you're making a big fuss'): 'Relax, no worries! I'm improving efficiency. I've already decided the direction, you just need to follow. What's there to worry about?'",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_28_story_blocking_one.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_29_TITLE",
		"title_en": "Page 29",
		"text_zh": "INTRO_DATA_PAGE_29_TEXT",
		"text_en": "Gloria (hurrying over, shielding ARK, addressing protagonist in gentle yet barbed tone): 'Oh dear, why are you angry again? No worries, the three of us just had a very smooth discussion. We can 'translate' the conclusion to One later, can't we? Why must you force everyone to cater to your so-called 'fairness'?'\nGloria (turning to One, revealing a patronizing smile): 'One, you don't mind, right? We're all working for the team.'\nOne (body stiffening slightly. To avoid breaking this 'harmony,' he forces a smile uglier than crying): '...I don't mind. I'll just follow arrangements.'\nVisual: The protagonist looks at One's accommodating appearance, feeling as if their heart was viciously stabbed. They see their past self, isolated in the camp, silently enduring.",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_29_story_gloria_pua.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_30_TITLE",
		"title_en": "Page 30",
		"text_zh": "INTRO_DATA_PAGE_30_TEXT",
		"text_en": "Scene: Deep in scrapyard, before a radiation obstacle.\nVisual: A huge acid-rain-corroded heavy metal blast door blocks the way. Someone must move it bare-handed. This is extremely exhausting dirty work with radiation burn risk.\nProtagonist (looking at aluminum-can-armored Donkey): 'Your turn. You said you're a knight? Move it.'\nDonkey (walking to the blast door, pretending to gesture, suddenly clutching his forehead with an extremely exaggerated pained expression): 'Ah! This evil aura... wait! My keen hero radar senses it! In the southeast of the scrapyard, a pure princess is being besieged by mutant rat swarms! She's calling my name!'",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_30_story_blast_door.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_31_TITLE",
		"title_en": "Page 31",
		"text_zh": "INTRO_DATA_PAGE_31_TEXT",
		"text_en": "Protagonist (pointing at the completely silent southeast, unable to take it anymore): 'Bullshit! There's not even a ghost there! You're just trying to escape this dirty, exhausting work!'\nDonkey (violently throwing off tattered red cloth cape, righteously shouting): 'How can vulgar mortals understand a hero's mission?! Moving a broken iron door, how can that compare with the great glory of rescuing a princess?! Fate is calling me, I must go ahead first!'\nVisual: After speaking, Donkey actually turns and runs, disappearing around a scrapyard corner like the wind.\nThe protagonist freezes in place, looking at ARK: 'This is your 'No worries' plan?!'\nARK (shrugging, still relaxed): 'No worries, it's just a door. Someone will move it eventually. Relax.'",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_31_story_donkey_runs.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_32_TITLE",
		"title_en": "Page 32",
		"text_zh": "INTRO_DATA_PAGE_32_TEXT",
		"text_en": "Visual: No one chases Donkey. ARK even starts humming a tune.\nOnly One. He silently walks to the dangerously glowing blast door, wordlessly bends down, and with bare hands without any protection, firmly grips the rusty edge, using all his strength to lift. Sharp rust pierces his palms, blood mixed with muddy water dripping.\nGloria (watching this scene, not helping, instead clasping hands and closing eyes to pray): 'Great FSM, please grant Donkey the power to rescue the princess, and please bless our current obstacle to be smoothly removed...'\nVisual ([Positive Energy Curse Triggered]): Just as Gloria devoutly prays, a rusty iron frame above the scrapyard that was already precariously hanging suddenly emits a harsh breaking sound due to some inexplicable physical decay, crashing down with a 'boom,' nearly hitting One who's moving the door!\n(The prayer didn't bring miracles, but instead accelerated the collapse of the surrounding environment.)",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_32_story_one_lifting_door.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_33_TITLE",
		"title_en": "Page 33",
		"text_zh": "INTRO_DATA_PAGE_33_TEXT",
		"text_en": "Protagonist (tackling One to dodge the iron frame, eyes reddening with fury): 'Enough!! Is this your so-called team?! Ark, your plan is a complete black box joke! You only say 'No worries' while watching teammates walk to their deaths! And Donkey, that deserter with a head full of feudal garbage, throwing all the most dangerous work to One!'\nVisual: The protagonist suddenly stands, pressing close to Gloria.\nProtagonist: 'And you! Don't you see that the more you pray, the faster this godforsaken place collapses?! This ship is sinking. Your blindness and shirking responsibility will get us all killed!'",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_33_story_protagonist_rage.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_34_TITLE",
		"title_en": "Page 34",
		"text_zh": "INTRO_DATA_PAGE_34_TEXT",
		"text_en": "Visual: The air instantly drops to freezing. ARK frowns, seeming to feel the protagonist has disrupted his 'No worries' atmosphere.\nAnd Gloria slowly opens her eyes. She doesn't look at injured One, doesn't look at the iron frame that nearly killed someone. She looks at the protagonist, no longer with gentleness, but with a superior, bone-chillingly disappointing gaze.\nAt this moment, Gloria's broken radio in her pocket, due to poor contact, automatically starts playing Teacher Chan's song, the gentle melody echoing in the dangerous scrapyard:\n'[Singing] Let me be my own protagonist... Success or failure depends on how I see it...'\nGloria (accompanied by Teacher Chan's singing, voice incredibly gentle yet wrapping around the protagonist's neck like a poisonous snake): 'Do you know how hurtful your words just were? I've always been tolerating you, even tolerating and accepting your usual double-speed, oppressively pressured way of speaking. But I've discovered I was wrong.'",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_34_story_gloria_disappointing_gaze.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_35_TITLE",
		"title_en": "Page 35",
		"text_zh": "INTRO_DATA_PAGE_35_TEXT",
		"text_en": "Gloria (stepping forward, eyes filled with moral judgment's oppressive weight, launching merciless manipulation): 'Have you forgotten love and tolerance? Donkey is just pursuing his dream. Ark just doesn't want to pressure everyone. But you? Your powerful negative energy is destroying our entire energy field! You always use your cold logic to nitpick others. You think you're solving problems? No, you're creating division!'\nGloria (eyes welling with tears, as if she's the biggest victim): 'I just came to this wasteland, living in fear every day. It's your negative energy that slowly led me into my first emotional low point in life! Actually, most times, as long as you treat others with kindness, don't stab people in the back, don't have such a heavy hatred heart, people wouldn't dislike you at all! Why can't you be more generous and entrust everything to the Flying Spaghetti Monster, to FSM?! Everyone can shine, you just haven't found the right place yet, though the right place might be where you are after you're dead.'\nVisual: The protagonist gasps heavily, lips trembling as they prepare to retort. Against Teacher Chan's 'Everyone can shine' background music, Gloria's words hammer down like a heavy weight, shattering the protagonist's last inner defenses.\nLooking at tears in Gloria's eyes, the long-standing desire for 'kindred spirits' and fear of loneliness completely backlashes at this moment.",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_35_story_protagonist_breakdown.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_36_TITLE",
		"title_en": "Page 36",
		"text_zh": "INTRO_DATA_PAGE_36_TEXT",
		"text_en": "Protagonist (pupils violently shaking, inner rationality completely collapsing): [She's crying... Did I drag her into an emotional low? Is my logic too cold? Do I speak too fast, too aggressively? So the problem has always been with me... My pathetic past turned me into this negative energy monster...]\nVisual: The protagonist looks at their own fists clenched in anger, suddenly feeling intense self-loathing. They slowly release their hands, legs weakening, actually half-kneeling in the muddy water.\nProtagonist (voice hoarse, filled with remorse and deep guilt): 'I'm sorry... Gloria. You're right. It's my fault. I'm too sensitive, my hatred heart too heavy. I... I've been living in past shadows, venting these negative energies on you all. Sorry, I'm truly sorry.'\nGloria (the coldness in her eyes instantly dissipates, replaced by an extremely loving, saintly smile. She extends her hand, gently stroking the protagonist's head): 'It's okay. As long as you're willing to admit your weakness, FSM will forgive you. Come, let's entrust these troubles we can't handle together to Him.'\n[Act IV: The Nominal Assembly and True Test]",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_36_story_submission_apology.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_37_TITLE",
		"title_en": "Page 37",
		"text_zh": "INTRO_DATA_PAGE_37_TEXT",
		"text_en": "Scene: Evening at the 'Greenhouse' shelter.\nVisual: After the scrapyard turmoil, the squad returns to camp. Donkey, who deserted in the face of battle, is already sitting in the greenhouse, holding a withered rose, boasting to Gloria about his false achievements.\nBut this time, the protagonist isn't angry. They sit quietly in the corner, eyes having lost their former sharpness, replaced by a post-brainwashing fervor and humility.\nGloria (turning the fire-hazard Life Bread lampshade to maximum brightness, face glowing with fanatical happiness): 'Dear family, today we experienced trials, but the universe's frequency has bound us tightly together again! Now, we will officially establish eternal team bonds witnessed by FSM!'",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_37_story_greenhouse_return_ceremony_setup.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_38_TITLE",
		"title_en": "Page 38",
		"text_zh": "INTRO_DATA_PAGE_38_TEXT",
		"text_en": "Visual: This is an absurdly ridiculous ceremony.\nDonkey (standing on one foot on a rusty barrel, raising the withered rose high): 'For glory! I shall use this invisible holy sword to cut through all thorns for GDA1! Princesses, wait for me!'\nARK (hands in pockets, relaxedly smiling): 'No worries, everything is under my control. Future scavenging plans will absolutely go smoothly.'\nGloria (holding the sunflower-painted broken garbage can, devoutly closing eyes): 'Great Flying Spaghetti Monster (FSM), thank You for granting us this perfect team. We vow to forever face everything with love and tolerance, rejecting all negative energy intrusions. Ramen.'\nDonkey & ARK (in unison): 'Ramen.'",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_37_story_greenhouse_return_ceremony_setup.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_39_TITLE",
		"title_en": "Page 39",
		"text_zh": "INTRO_DATA_PAGE_39_TEXT",
		"text_en": "Visual: Camera switches to protagonist's first-person subjective view (player perspective).\nThe protagonist watches this absurd scene before them: a deserter, a blindly commanding blind man, and a saint forcing everyone to be optimistic. But at this moment, the protagonist's heart no longer holds half a trace of sarcasm.\nThey glance at One still bleeding in the corner, heart welling up not with sympathy but self-blame for past 'meddling.'\nProtagonist (inner monologue, filled with post-manipulation morbid devotion): [I must pray. This world is broken because I'm not kind enough, because I'm full of negative energy. I must keep up with Gloria's frequency. I must use love and tolerance to make up for my mistakes. FSM, please purify me.]\nProtagonist (eyes tightly closed, hands forcefully clasped, tone incredibly sincere and fervent): 'Ramen! I believe in the Law of Attraction. I believe everything will get better!'\nVisual ([Positive Energy Curse Triggered]): Just as the protagonist sincerely shouts this positive energy prayer, a ghastly green lightning suddenly strikes outside the greenhouse! The surrounding radiation concentration visibly spikes, even the Life Bread lampshade begins emitting acrid black smoke.\n(The more they forcibly create positive energy, the more violently the world's 'entropy increase' rages!)",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_39_story_protagonist_pov_brainwashed.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_40_TITLE",
		"title_en": "Page 40",
		"text_zh": "INTRO_DATA_PAGE_40_TEXT",
		"text_en": "Visual: Just as the protagonist is immersed in self-moved redemption, \n'Woo, woo, woo, !!!'\nOutside the camp, the highest-level crimson air raid alarm suddenly sounds! Violent acid rain mixed with a giant mutant beast's roar instantly tears through the greenhouse's fragile cardboard walls! The first real life-or-death crisis has arrived!\nProtagonist (walking toward the mutant beast, neurotically muttering): 'This is just a test... all because my negative energy attracted this test. I must use love and tolerance to eliminate everything! FSM will protect us!'\nCamera suddenly pulls back, screen instantly plunging into pure black.\nBlood-red subtitles slowly emerge in the darkness:\n[Welcome to the 'Glorious Deliverance Agency.'][You have become one of them. Good luck, because in this curse called 'positive energy,' you have nowhere to escape.]\n[Game title logo crashes down, accompanied by Teacher Chan's hollow 'Everyone can shine' and explosive industrial metal music!]\n[THE END]",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_40_story_departure_one_luggage.png",
	},
	{
		"title_zh": "INTRO_DATA_PAGE_41_TITLE",
		"title_en": "Page 41",
		"text_zh": "INTRO_DATA_PAGE_41_TEXT",
		"text_en": "Visual: Sirens still wail as the protagonist, One, Gloria, Ark, and Donkey stand shoulder to shoulder outside the greenhouse, backlit smog outlining their silhouettes. Though exhausted and full of unresolved tension, everyone lifts their gaze forward, ready to face the real challenge together.\nSubtitle: 'This time, they stand together.'",
		"image_path": "res://1.Codebase/src/assets/ui/intro/page_41_story_final_logo.png",
	},
]
static func _tr(key: String) -> String:
	if LocalizationManager:
		return LocalizationManager.get_translation(key)
	return key
static func get_story_pages() -> Array[Dictionary]:
	return STORY_PAGES.duplicate(true)
static func get_texture_for_path(path: String) -> Texture2D:
	var normalized := path.strip_edges()
	if normalized.is_empty():
		return null
	if STORY_TEXTURES.has(normalized):
		return STORY_TEXTURES[normalized]
	return null
