extends Node
const StoryChoiceController = preload("res://1.Codebase/src/scripts/ui/story_choice_controller.gd")
const StoryStateController = preload("res://1.Codebase/src/scripts/ui/story_state_controller.gd")
const StoryOverlayController = preload("res://1.Codebase/src/scripts/ui/story_overlay_controller.gd")
func test_choice_controller_sets_context_correctly():
	print("[Test] Testing prayer context from choice selection")
	var mock_story_scene = Control.new()
	add_child(mock_story_scene)
	var state_controller = StoryStateController.new(mock_story_scene)
	mock_story_scene.set("state_controller", state_controller)
	var choice_controller = StoryChoiceController.new(mock_story_scene)
	var initial_context = state_controller.get_prayer_context()
	print("[Test] Initial prayer context: %s" % initial_context)
	assert(initial_context == "mission", "Initial context should be 'mission'")
	if mock_story_scene and mock_story_scene.get("state_controller"):
		mock_story_scene.get("state_controller").set_prayer_context(choice_controller.PRAYER_CONTEXT_MISSION)
	var context_after_choice = state_controller.get_prayer_context()
	print("[Test] Prayer context after choice selection: %s" % context_after_choice)
	assert(context_after_choice == "mission", "Context should be 'mission' after choice selection")
	print("[Test] SUCCESS: Choice controller sets context correctly through state_controller")
	mock_story_scene.queue_free()
func test_night_overlay_sets_context_correctly():
	print("[Test] Testing prayer context from night overlay")
	var mock_story_scene = Control.new()
	add_child(mock_story_scene)
	var state_controller = StoryStateController.new(mock_story_scene)
	mock_story_scene.set("state_controller", state_controller)
	var initial_context = state_controller.get_prayer_context()
	print("[Test] Initial prayer context: %s" % initial_context)
	assert(initial_context == "mission", "Initial context should be 'mission'")
	if mock_story_scene and mock_story_scene.get("state_controller"):
		mock_story_scene.get("state_controller").set_prayer_context("night")
	var context_after_night = state_controller.get_prayer_context()
	print("[Test] Prayer context after night overlay request: %s" % context_after_night)
	assert(context_after_night == "night", "Context should be 'night' after night overlay request")
	print("[Test] SUCCESS: Night overlay sets context correctly through state_controller")
	mock_story_scene.queue_free()
func test_context_consistency():
	print("[Test] Testing context consistency between different entry points")
	var mock_story_scene = Control.new()
	add_child(mock_story_scene)
	var state_controller = StoryStateController.new(mock_story_scene)
	mock_story_scene.set("state_controller", state_controller)
	state_controller.set_prayer_context("mission")
	assert(state_controller.get_prayer_context() == "mission", "Context should be 'mission'")
	state_controller.set_prayer_context("night")
	assert(state_controller.get_prayer_context() == "night", "Context should be 'night'")
	state_controller.set_prayer_context("mission")
	assert(state_controller.get_prayer_context() == "mission", "Context should be back to 'mission'")
	print("[Test] SUCCESS: Context switching works consistently")
	mock_story_scene.queue_free()
func _ready():
	print("===== Prayer Context Fix Test Suite =====")
	test_choice_controller_sets_context_correctly()
	print("")
	test_night_overlay_sets_context_correctly()
	print("")
	test_context_consistency()
	print("")
	print("===== All Tests Passed =====")
	queue_free()
