extends Node
var tests_passed: int = 0
var tests_failed: int = 0
var initial_font_size: int
var initial_multiplier: float
func _ready() -> void:
	print("[FontManagerTest] Starting FontManager unit tests...")
	await get_tree().process_frame
	if not FontManager:
		print("[FontManagerTest]  FAIL: FontManager autoload not found")
		queue_free()
		return
	initial_font_size = FontManager.get_font_size()
	initial_multiplier = FontManager.get_multiplier()
	_test_initialization()
	_test_font_size_presets()
	_test_set_font_size()
	_test_get_multiplier()
	_test_get_font_size_name()
	_test_get_scaled_font_size()
	_test_apply_to_label()
	_test_apply_to_button()
	_test_apply_to_rich_text()
	await _test_signal_emission()
	await _test_save_load_settings()
	_test_invalid_font_size()
	_test_font_variation_validation()
	FontManager.set_font_size(initial_font_size)
	print("[FontManagerTest] All tests completed.")
	queue_free()
func _test_initialization() -> void:
	print("[Test] Initialization...")
	_assert(FontManager != null, "FontManager should exist as autoload")
	_assert(FontManager.font_size_multipliers is Dictionary, "font_size_multipliers should be Dictionary")
	_assert(FontManager.current_font_size >= 0, "current_font_size should be valid")
	_assert(FontManager.current_multiplier > 0.0, "current_multiplier should be positive")
	_assert(FontManager.FALLBACK_FONT != null, "FALLBACK_FONT should be loaded")
	_assert(FontManager.REGISTERED_FONTS is Array, "REGISTERED_FONTS should be Array")
	print("[Test] Initialization PASSED ")
func _test_font_size_presets() -> void:
	print("[Test] Font size presets...")
	_assert(FontManager.FontSize.TINY == 0, "TINY should be 0")
	_assert(FontManager.FontSize.SMALL == 1, "SMALL should be 1")
	_assert(FontManager.FontSize.NORMAL == 2, "NORMAL should be 2")
	_assert(FontManager.FontSize.LARGE == 3, "LARGE should be 3")
	_assert(FontManager.FontSize.HUGE == 4, "HUGE should be 4")
	_assert(FontManager.font_size_multipliers[FontManager.FontSize.TINY] == 0.75, "TINY multiplier should be 0.75")
	_assert(FontManager.font_size_multipliers[FontManager.FontSize.SMALL] == 0.85, "SMALL multiplier should be 0.85")
	_assert(FontManager.font_size_multipliers[FontManager.FontSize.NORMAL] == 1.0, "NORMAL multiplier should be 1.0")
	_assert(FontManager.font_size_multipliers[FontManager.FontSize.LARGE] == 1.25, "LARGE multiplier should be 1.25")
	_assert(FontManager.font_size_multipliers[FontManager.FontSize.HUGE] == 1.5, "HUGE multiplier should be 1.5")
	print("[Test] Font size presets PASSED ")
func _test_set_font_size() -> void:
	print("[Test] Set font size...")
	FontManager.set_font_size(FontManager.FontSize.LARGE)
	_assert(FontManager.get_font_size() == FontManager.FontSize.LARGE, "Should set to LARGE")
	_assert(FontManager.get_multiplier() == 1.25, "Multiplier should be 1.25")
	FontManager.set_font_size(FontManager.FontSize.TINY)
	_assert(FontManager.get_font_size() == FontManager.FontSize.TINY, "Should set to TINY")
	_assert(FontManager.get_multiplier() == 0.75, "Multiplier should be 0.75")
	FontManager.set_font_size(FontManager.FontSize.NORMAL)
	_assert(FontManager.get_font_size() == FontManager.FontSize.NORMAL, "Should set to NORMAL")
	_assert(FontManager.get_multiplier() == 1.0, "Multiplier should be 1.0")
	print("[Test] Set font size PASSED ")
func _test_get_multiplier() -> void:
	print("[Test] Get multiplier...")
	FontManager.set_font_size(FontManager.FontSize.HUGE)
	var multiplier = FontManager.get_multiplier()
	_assert(multiplier is float, "Multiplier should be float")
	_assert(multiplier == 1.5, "HUGE multiplier should be 1.5")
	FontManager.set_font_size(FontManager.FontSize.SMALL)
	multiplier = FontManager.get_multiplier()
	_assert(multiplier == 0.85, "SMALL multiplier should be 0.85")
	print("[Test] Get multiplier PASSED ")
func _test_get_font_size_name() -> void:
	print("[Test] Get font size name...")
	FontManager.set_font_size(FontManager.FontSize.TINY)
	_assert(FontManager.get_font_size_name() == "Tiny", "TINY name should be 'Tiny'")
	FontManager.set_font_size(FontManager.FontSize.SMALL)
	_assert(FontManager.get_font_size_name() == "Small", "SMALL name should be 'Small'")
	FontManager.set_font_size(FontManager.FontSize.NORMAL)
	_assert(FontManager.get_font_size_name() == "Normal", "NORMAL name should be 'Normal'")
	FontManager.set_font_size(FontManager.FontSize.LARGE)
	_assert(FontManager.get_font_size_name() == "Large", "LARGE name should be 'Large'")
	FontManager.set_font_size(FontManager.FontSize.HUGE)
	_assert(FontManager.get_font_size_name() == "Huge", "HUGE name should be 'Huge'")
	print("[Test] Get font size name PASSED ")
func _test_get_scaled_font_size() -> void:
	print("[Test] Get scaled font size...")
	FontManager.set_font_size(FontManager.FontSize.NORMAL)
	_assert(FontManager.get_scaled_font_size(16) == 16, "NORMAL: 16 should scale to 16")
	_assert(FontManager.get_scaled_font_size(24) == 24, "NORMAL: 24 should scale to 24")
	FontManager.set_font_size(FontManager.FontSize.LARGE)
	_assert(FontManager.get_scaled_font_size(16) == 20, "LARGE: 16 should scale to 20")
	_assert(FontManager.get_scaled_font_size(24) == 30, "LARGE: 24 should scale to 30")
	FontManager.set_font_size(FontManager.FontSize.TINY)
	_assert(FontManager.get_scaled_font_size(16) == 12, "TINY: 16 should scale to 12")
	_assert(FontManager.get_scaled_font_size(20) == 15, "TINY: 20 should scale to 15")
	FontManager.set_font_size(FontManager.FontSize.HUGE)
	_assert(FontManager.get_scaled_font_size(16) == 24, "HUGE: 16 should scale to 24")
	_assert(FontManager.get_scaled_font_size(10) == 15, "HUGE: 10 should scale to 15")
	print("[Test] Get scaled font size PASSED ")
func _test_apply_to_label() -> void:
	print("[Test] Apply to label...")
	var label = Label.new()
	add_child(label)
	FontManager.set_font_size(FontManager.FontSize.LARGE)
	FontManager.apply_to_label(label, 16)
	_assert(label.has_theme_font_size_override("font_size"), "Label should have font size override")
	var applied_size = label.get_theme_font_size("font_size")
	_assert(applied_size == 20, "Label font size should be scaled to 20 (16 * 1.25)")
	FontManager.apply_to_label(label, 24)
	applied_size = label.get_theme_font_size("font_size")
	_assert(applied_size == 30, "Label font size should be scaled to 30 (24 * 1.25)")
	label.queue_free()
	print("[Test] Apply to label PASSED ")
func _test_apply_to_button() -> void:
	print("[Test] Apply to button...")
	var button = Button.new()
	add_child(button)
	FontManager.set_font_size(FontManager.FontSize.SMALL)
	FontManager.apply_to_button(button, 16)
	_assert(button.has_theme_font_size_override("font_size"), "Button should have font size override")
	var applied_size = button.get_theme_font_size("font_size")
	var expected_size = int(16 * 0.85)
	_assert(applied_size == expected_size, "Button font size should be scaled correctly")
	button.queue_free()
	print("[Test] Apply to button PASSED ")
func _test_apply_to_rich_text() -> void:
	print("[Test] Apply to rich text...")
	var rich_text = RichTextLabel.new()
	add_child(rich_text)
	FontManager.set_font_size(FontManager.FontSize.HUGE)
	FontManager.apply_to_rich_text(rich_text, 16)
	_assert(rich_text.has_theme_font_size_override("normal_font_size"), "RichTextLabel should have normal_font_size override")
	var applied_size = rich_text.get_theme_font_size("normal_font_size")
	_assert(applied_size == 24, "RichTextLabel font size should be scaled to 24 (16 * 1.5)")
	rich_text.queue_free()
	print("[Test] Apply to rich text PASSED ")
func _test_signal_emission() -> void:
	print("[Test] Signal emission...")
	var state = {"received": false, "scale": 0.0}
	var signal_handler = func(scale: float):
		state["received"] = true
		state["scale"] = scale
	FontManager.font_size_changed.connect(signal_handler)
	FontManager.set_font_size(FontManager.FontSize.LARGE)
	await get_tree().create_timer(0.05).timeout
	_assert(state["received"], "font_size_changed signal should be emitted")
	_assert(state["scale"] == 1.25, "Signal should contain correct scale value")
	FontManager.font_size_changed.disconnect(signal_handler)
	print("[Test] Signal emission PASSED ")
func _test_save_load_settings() -> void:
	print("[Test] Save/load settings...")
	FontManager.set_font_size(FontManager.FontSize.HUGE)
	FontManager.save_font_settings()
	await get_tree().create_timer(0.1).timeout
	FontManager.set_font_size(FontManager.FontSize.TINY)
	_assert(FontManager.get_font_size() == FontManager.FontSize.TINY, "Should be TINY before load")
	FontManager.load_font_settings()
	_assert(FontManager.get_font_size() == FontManager.FontSize.HUGE, "Should restore HUGE from save")
	_assert(FontManager.get_multiplier() == 1.5, "Should restore multiplier from save")
	print("[Test] Save/load settings PASSED ")
func _test_invalid_font_size() -> void:
	print("[Test] Invalid font size...")
	var original_size = FontManager.get_font_size()
	FontManager.set_font_size(999)
	_assert(FontManager.get_font_size() == original_size, "Invalid font size should not change current size")
	FontManager.set_font_size(FontManager.FontSize.NORMAL)
	print("[Test] Invalid font size PASSED ")
func _test_font_variation_validation() -> void:
	print("[Test] Font variation validation...")
	var variation := FontVariation.new()
	_assert(FontManager.get_safe_font(variation) == FontManager.FALLBACK_FONT, "FontVariation without base font should fall back")
	variation.base_font = FontManager.FALLBACK_FONT
	_assert(FontManager.get_safe_font(variation) == variation, "FontVariation with valid base font should be accepted")
	print("[Test] Font variation validation PASSED ")
func _assert(condition: bool, message: String) -> void:
	if condition:
		tests_passed += 1
		print("    PASS  %s" % message)
	else:
		tests_failed += 1
		print("    FAIL  %s" % message)
